services:
  python-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=JobAnalysis
      - DB_USER=postgres
      - DB_PASSWORD=Arfanshaikh@10
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=JobAnalysis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Arfanshaikh@10
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data: