name: 'job_analysis'
version: '1.0.0'
config-version: 2

profile: 'job_analysis'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  job_analysis:
    staging:
      +materialized: view