job_analysis:
  outputs:
    dev:
      dbname: Job_Analysis
      host: postgres-db
      pass: Arfanshaikh@10
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
